name: pre-commit-tests@TF

on:
  pull_request:
    branches:
    - master
jobs:
  sanity:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Get sha
        id: sha
        run: |
          echo "::set-output name=SHA::$(git rev-parse HEAD)"

      - name: Install needed dependences for sanity checks
        id: sched_test
        run: |
          sudo apt-get update && sudo apt-get -y install curl jq make git shellcheck python3 python3-pip
          pip3 install pre-commit

      - name: Run Sanity pre-commit tests
        continue-on-error: true
        id: pre_commit_tests
        run: |
          set +e
          make pre-commit-check
          echo ::set-output name=exit_status::$?
